CREATE TABLE [stg].[accidents](
	[accident_index] [varchar](50) NULL,
	[accident_year] [bigint] NULL,
	[accident_reference] [varchar](50) NULL,
	[location_easting_osgr] [varchar](50) NULL,
	[location_northing_osgr] [varchar](50) NULL,
	[longitude] [varchar](50) NULL,
	[latitude] [varchar](50) NULL,
	[police_force] [bigint] NULL,
	[accident_severity] [bigint] NULL,
	[number_of_vehicles] [bigint] NULL,
	[number_of_casualties] [bigint] NULL,
	[acc_date] [date] NULL,
	[day_of_week] [bigint] NULL,
	[time] [varchar](50) NULL,
	[local_authority_district] [bigint] NULL,
	[local_authority_ons_district] [varchar](50) NULL,
	[local_authority_highway] [varchar](50) NULL,
	[first_road_class] [bigint] NULL,
	[first_road_number] [bigint] NULL,
	[road_type] [bigint] NULL,
	[speed_limit] [bigint] NULL,
	[junction_detail] [bigint] NULL,
	[junction_control] [bigint] NULL,
	[second_road_class] [bigint] NULL,
	[second_road_number] [bigint] NULL,
	[pedestrian_crossing_human_control] [bigint] NULL,
	[pedestrian_crossing_physical_facilities] [bigint] NULL,
	[light_conditions] [bigint] NULL,
	[weather_conditions] [bigint] NULL,
	[road_surface_conditions] [bigint] NULL,
	[special_conditions_at_site] [bigint] NULL,
	[carriageway_hazards] [bigint] NULL,
	[urban_or_rural_area] [bigint] NULL,
	[did_police_officer_attend_scene_of_accident] [bigint] NULL,
	[trunk_road_flag] [bigint] NULL,
	[lsoa_of_accident_location] [varchar](50) NULL
) 
GO


